### ISSUE TITLE
Training not proper

### ISSUE THREAD

**Issue by Karthikkadivela** [Vigneswaran-Chandrasekaran/handwriting_generation#1]
I trained the files present in oscillator folder. But the expected results weren't obtained. The first word is getting generated but others are failing to generate , and its just scribbles getting generated. Can you let me know which are the actual files to be used to train so as to obtain output as obtained in (https://github.com/Grzego/handwriting-generation).
Thanks in advance :)

**Comment by vigneswaran-chandrasekaran** [comment]
Hi, I changed the repository with workable files. Generally, you need to train for more epochs to get better results
